### ISSUE TITLE
TZ setting is ignored

### ISSUE THREAD

**Issue by PapiFed** [hotcereal/time-quick-fix#1]
Whatever value is entered for "TZ" is not considered and when running the app the time is always adjusted based on TZ=UTC-0

**Comment by hotcereal** [comment]
This app should be deprecated by now. The onionOS most recent beta has a timezone app built in, I believe. Release Onion V4.2.0-beta-dev · OnionUI/Oniongithub.comOn Jul 10, 2023, at 8:47 PM, PapiFed ***@***.***> wrote:﻿
Whatever value is entered for "TZ" is not considered and when running the app the time is always adjusted based on TZ=UTC-0

**Comment by PapiFed** [comment]
I am using the 4.2 beta but the time each time I boot is never correct

**Comment by PapiFed** [comment]
I figured it out... The app is not using the TZ value launch.sh file but the setting done in the OnionOS Tweaks instead.
